'use strict';

(function () {
  window.data = {
    products: [
      {
        id: 1,
        pageSrc: 'product1.html',
        name: 'mango people t-shirt',
        img: 'img/product__img1.jpg',
        color: 'Red',
        size: 'XL',
        material: 'cotton',
        designer: 'binburhan',
        delivery: 'free',
        price: 10.00,
      },
      {
        id: 2,
        pageSrc: 'product2.html',
        name: 'mango people t-shirt',
        img: ['img/product__img2.jpg', 'img/similar-product__item1--single-page.jpg'],
        color: 'Green',
        size: 'M',
        material: 'cotton',
        designer: 'binburhan',
        delivery: 'free',
        price: 20.00,
      },
      {
        id: 3,
        pageSrc: 'product3.html',
        name: 'mango people t-shirt',
        img: ['img/product__img3.jpg', 'img/similar-product__item2--single-page.jpg',
          'img/similar-product__item3--single-page.jpg', 'img/similar-product__item4--single-page.jpg'],
        color: 'Red',
        size: 'S',
        material: 'cotton',
        designer: 'binburhan',
        delivery: 'free',
        price: 56.00,
      },
      {
        id: 4,
        pageSrc: 'product4.html',
        name: 'mango people t-shirt',
        img: ['img/product__img4.jpg', 'img/featured__item1.jpg', 'img/featured__item2.jpg', 'img/featured__item3.jpg',
          'img/featured__item4.jpg', 'img/featured__item5.jpg', 'img/featured__item6.jpg', 'img/featured__item7.jpg',
          'img/featured__item8.jpg'],
        color: 'Blue',
        size: 'XL',
        material: 'cotton',
        designer: 'binburhan',
        delivery: 'free',
        price: 23.00,
      },
      {
        id: 5,
        pageSrc: 'product5.html',
        name: 'mango people t-shirt',
        img: 'img/product__img5.jpg',
        color: 'Black',
        size: 'M',
        material: 'cotton',
        designer: 'binburhan',
        delivery: 'free',
        price: 45.00,
      },
      {
        id: 6,
        pageSrc: 'product6.html',
        name: 'mango people t-shirt',
        img: ['img/product__img6.jpg', 'img/featured__item2.jpg', 'img/featured__item3.jpg'],
        color: 'Green',
        size: 'S',
        material: 'cotton',
        designer: 'binburhan',
        delivery: 'free',
        price: 67.00,
      },
      {
        id: 7,
        pageSrc: 'product7.html',
        name: 'mango people t-shirt',
        img: 'img/product__img7.jpg',
        color: 'White',
        size: 'XL',
        material: 'cotton',
        designer: 'binburhan',
        delivery: 'free',
        price: 76.00,
      },
      {
        id: 8,
        pageSrc: 'product8.html',
        name: 'mango people t-shirt',
        img: ['img/product__img8.jpg', 'img/featured__item4.jpg', 'img/featured__item5.jpg', 'img/featured__item6.jpg'],
        color: 'Red',
        size: 'L',
        material: 'cotton',
        designer: 'binburhan',
        delivery: 'free',
        price: 32.00,
      },
      {
        id: 9,
        pageSrc: 'product9.html',
        name: 'mango people t-shirt',
        img: 'img/product__img9.jpg',
        color: 'Yellow',
        size: 'XL',
        material: 'cotton',
        designer: 'binburhan',
        delivery: 'free',
        price: 47.00,
      }
    ]
  };
})();
